# name of the software
name: mockzilla
remote_theme: allejo/jekyll-docs-theme@v1.0.0-beta.4

project:
  version: 0.6.0
  download_url: https://www.npmjs.com/package/mockzilla
  download_text: Install on NPM

license:
  software: zlib/libpng License
  software_url: https://opensource.org/licenses/Zlib

  # docs: CC BY 3.0
  # docs_url: https://creativecommons.org/licenses/by/3.0/

links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/lusito/mockzilla
    - title: NPM
      icon: npm
      brand: true
      url: https://www.npmjs.com/package/mockzilla
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/lusito/mockzilla
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/lusito/mockzilla
    - title: Issues
      icon: bug
      url: https://github.com/lusito/mockzilla/issues?state=open
    - title: NPM
      icon: npm
      url: https://www.npmjs.com/package/mockzilla

ui:
  mode: 'auto' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#a20000"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#080331"
      color2: "#673051"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'

social:
  github:
    user: lusito
    repo: mockzilla
  twitter:
    enabled: false
    via:
    hash:
    account:
  facebook:
    enabled: false
    profileUrl:

# Build settings
markdown: kramdown
